# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tools/custom_byteblock.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tools/custom_byteblock.proto',
  package='rm_custom',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1ctools/custom_byteblock.proto\x12\trm_custom\"\x1f\n\x0f\x43ustomByteBlock\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\" \n\x10\x43ustomByteBlockE\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x62\x06proto3'
)




_CUSTOMBYTEBLOCK = _descriptor.Descriptor(
  name='CustomByteBlock',
  full_name='rm_custom.CustomByteBlock',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='rm_custom.CustomByteBlock.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=74,
)


_CUSTOMBYTEBLOCKE = _descriptor.Descriptor(
  name='CustomByteBlockE',
  full_name='rm_custom.CustomByteBlockE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='rm_custom.CustomByteBlockE.data', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=108,
)

DESCRIPTOR.message_types_by_name['CustomByteBlock'] = _CUSTOMBYTEBLOCK
DESCRIPTOR.message_types_by_name['CustomByteBlockE'] = _CUSTOMBYTEBLOCKE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CustomByteBlock = _reflection.GeneratedProtocolMessageType('CustomByteBlock', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMBYTEBLOCK,
  '__module__' : 'tools.custom_byteblock_pb2'
  # @@protoc_insertion_point(class_scope:rm_custom.CustomByteBlock)
  })
_sym_db.RegisterMessage(CustomByteBlock)

CustomByteBlockE = _reflection.GeneratedProtocolMessageType('CustomByteBlockE', (_message.Message,), {
  'DESCRIPTOR' : _CUSTOMBYTEBLOCKE,
  '__module__' : 'tools.custom_byteblock_pb2'
  # @@protoc_insertion_point(class_scope:rm_custom.CustomByteBlockE)
  })
_sym_db.RegisterMessage(CustomByteBlockE)


# @@protoc_insertion_point(module_scope)
